import React from "react";
import Head from "next/head";
import Link from "next/link";

import styles from "./Layout.module.css";
import Image from "next/image";
import logo from "../../assets/logo.svg";

export const Layout = ({ children, title = "World Ranks" }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Link href="/games" passHref>
          <Image src={logo} alt="world ranks icon" />
        </Link>
      </header>

      <main className={styles.main}>{children}</main>

      <footer className={styles.footer}>footer</footer>
    </div>
  );
};
